### ISSUE TITLE
Running pymcmcstat using results from a previous run

### ISSUE THREAD

**Issue by rayadastidar** [prmiles/pymcmcstat#81]
Hi, I need to run pymcmcstat in multiple batches, i.e., say first I run it for 500 iterations and use the results from the previous output to the next batch of 500 iterations. This is because I am entitled to a limited running time in the institute cluster. It seems to me that 'run_simulation(use_previous_results=True)' could help, but I am not sure how to use this when writing the second code which takes the generated output from the first code to rerun pymcmcstat. Simply using 'run_simulation(use_previous_results=True)' in the second code says that the code did not find any previous result. Currently, I have run the code for 2000 iterations and I want to run the code for another 2000 iterations.
Can you please suggest a way of doing this?

**Comment by prmiles** [comment]
@rayadastidar Excellent question!  I've put together a fairly rough example and added it to the examples repository.  You can see the notebook on [NBViewer](https://nbviewer.jupyter.org/github/prmiles/pymcmcstat_examples/blob/master/Restarting_Simulations.ipynb) for a basic outline of how you can import results from a previous simulation in order to initialize a new one.  If the link to NBViewer doesn't work, then you should also be able to see it directly on [GitHub](https://github.com/prmiles/pymcmcstat_examples/blob/f7306506bf5d16e619c0ba285c6c3708a5c99783/Restarting_Simulations.ipynb).

I'll admit that it is not the most elegant solution, but I believe it will work for what you need.  Each time you restart the simulation a new result folder will be created, which you will then need to reference when you go to restart again.

Please let me know if this works for you and feel free to ask more questions.

**Comment by rayadastidar** [comment]
Thanks, this works for me.
