### ISSUE TITLE
Using a log likelihood function in place of sos function

### ISSUE THREAD

**Issue by isa-a** [prmiles/pymcmcstat#97]
I wish to utilise a log likelihood (or likelihood) function instead of the sum of squares function. How is it possible to do this?

For example I have two lognormal distributions, and I sum the log likelihoods from these two together to get one log likelihood. I can take an expontential to get likelihood if need be. How would I work this into the most basic example of MCMC?

```
muPrev, sigmaPrev = 400, 40 #I
muInc, sigmaInc = 300, 30 #cInc
n = 10000

# logPrev = np.random.lognormal(np.log((muPrev**2) / (muPrev**2 + sigmaPrev**2)**0.5), (np.log(1 + (sigmaPrev**2 / muPrev**2)))**0.5, n) #lognormal
# logInc = np.random.lognormal(np.log((muInc**2) / (muInc**2 + sigmaInc**2)**0.5), (np.log(1 + (sigmaInc**2 / muInc**2)))**0.5, n) #lognormal

xPrev = 400 #value of x in formula for log of pdf
xInc = 300

logmuPrev = np.log((muPrev**2) / (muPrev**2 + sigmaPrev**2)**0.5) #lognormal params
logsdPrev = (np.log(1 + (sigmaPrev**2 / muPrev**2)))**0.5

logmuInc = np.log((muInc**2) / (muInc**2 + sigmaInc**2)**0.5)#lognormal params
logsdInc = (np.log(1 + (sigmaInc**2 / muInc**2)))**0.5

L_prev = -0.5*((np.log(400) - logmuPrev) / logsdPrev)**2 - np.log(400* logsdPrev * (2*math.pi)**0.5) #log of pdf for prev and inc
L_inc = -0.5*((np.log(300) - logmuInc) / logsdInc)**2 - np.log(300* logsdInc * (2*math.pi)**0.5)

logsum = L_prev + L_inc #summing logs
np.exp(logsum) #exp for likelihood

```

**Comment by prmiles** [comment]
Sorry for the delay - this package is not actively supported at this time.  You should be able to use a log-likelihood function by returning the log of the sum-of-squares error instead of the sum-of-squares error.  So, something like this:

```
def sum_of_squares(...)
    ...
    return np.log(ssq)
```

If you are looking for a more flexible framework, I also recommend [PyMC3](https://www.pymc.io/projects/docs/en/v3/index.html).  If you really want to use the DRAM algorithm, then I'd also recommend [PyApprox](https://github.com/sandialabs/pyapprox).  Hope that helps, and sorry again for the delay!
